"""Homework 3 - the pipeline runner. SUPPLIED: do not edit this file.

Run it from the project folder:

    uv run python pipeline.py

What it does, in this order, every time:

  1. deletes data/silver/, data/gold/ and output/, so every run makes every table again from data/raw/;
  2. silver: runs scripts/clean_owid.py, scripts/clean_eurostat.py, scripts/clean_worldbank.py - each one's run(con);
  3. registers every file in data/silver/ as a view: data/silver/eurostat.parquet is silver.eurostat, and so on;
  4. checks: runs the four families in scripts/checks.py - check_key, check_domain, check_count,
     check_reconciliation - and STOPS at the first family that returns a record with action "stop";
  5. gold: runs scripts/report.py's run(con), then registers data/gold/ as gold.<name>;
  6. writes output/checks_report.json - always, even when the run stops or crashes.

A stage that still says `raise NotImplementedError` is reported as "not written yet" and skipped, so the pipeline
runs from the first day. The mutation harness that grades the verification criterion reads
output/checks_report.json (README: "The checks report").
"""
from __future__ import annotations

import importlib
import json
import math
import os
import shutil
import sys
import traceback
from pathlib import Path

import duckdb

ROOT = Path(__file__).resolve().parent
os.chdir(ROOT)                      # every path in this project is relative to the project folder
sys.path.insert(0, str(ROOT))       # so that `import scripts.clean_owid` works

CLEANERS = ("clean_owid", "clean_eurostat", "clean_worldbank")
FAMILIES = ("key", "domain", "count", "reconciliation")
ACTIONS = ("stop", "quarantine", "dedupe", "exclude", "flag", "pass")
FIELDS = ("family", "check", "subject", "observed", "threshold", "action")
DESTINATIONS = ("rejected", "excluded", "quarantined", "aggregate", "retained")
GENERATED = (Path("data/silver"), Path("data/gold"), Path("output"))
REPORT = Path("output/checks_report.json")


def fresh_start() -> None:
    for d in GENERATED:
        if d.exists():
            shutil.rmtree(d)
        d.mkdir(parents=True)


def register(con: duckdb.DuckDBPyConnection, schema: str, folder: Path) -> list[str]:
    """Make every .parquet and .csv file in `folder` queryable as schema.<file name without extension>."""
    con.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")
    names = []
    for f in sorted(folder.glob("*")):
        if f.suffix == ".parquet":
            source = f"read_parquet('{f.as_posix()}')"
        elif f.suffix == ".csv":
            source = f"read_csv('{f.as_posix()}', header = true)"
        else:
            continue
        con.execute(f"CREATE OR REPLACE VIEW {schema}.{f.stem} AS SELECT * FROM {source}")
        names.append(f"{schema}.{f.stem}")
    return names


def jsonable(x):
    """A value json can write: numbers stay numbers (NaN becomes null), text stays text."""
    if x is None or isinstance(x, (bool, int, str)):
        return x
    if isinstance(x, float):
        return x if math.isfinite(x) else None
    try:
        return float(x)             # Decimal, numpy numbers
    except (TypeError, ValueError):
        return str(x)


def as_records(returned, family: str) -> list[dict]:
    """Check what a family function returned: a list of records made with checks.record(...)."""
    if returned is None:
        returned = []
    if isinstance(returned, dict):
        returned = [returned]
    out = []
    for r in returned:
        if not isinstance(r, dict):
            raise TypeError(f"check_{family} must return a list of records (dicts); got {type(r).__name__}")
        missing = [k for k in FIELDS if k not in r]
        if missing:
            raise ValueError(f"check_{family}: a record has no {', '.join(missing)}: {r}")
        if r["family"] != family:
            raise ValueError(f"check_{family} returned a record with family {r['family']!r}: "
                             f"every record check_{family} returns has family {family!r}")
        if r["action"] not in ACTIONS:
            raise ValueError(f"check_{family}: action {r['action']!r} is not one of {', '.join(ACTIONS)}")
        out.append({k: jsonable(v) for k, v in r.items()})
    return out


def fmt(x) -> str:
    if isinstance(x, bool) or x is None:
        return str(x)
    if isinstance(x, int):
        return f"{x:,}"
    if isinstance(x, float):
        return f"{x:,.6g}" if abs(x) < 1e6 else f"{x:,.0f}"
    return str(x)


def print_accounting(source: str, acc: dict) -> None:
    parts = [f"{d} {fmt(acc[d])}" for d in DESTINATIONS if d in acc]
    extra = [f"{k} {fmt(v)}" for k, v in acc.items() if k != "in" and k not in DESTINATIONS]
    line = f"    accounting: in {fmt(acc.get('in'))} = " + " + ".join(parts)
    print(line + (f"   ({'; '.join(extra)})" if extra else ""))


def write_report(state: dict) -> None:
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(json.dumps(state, indent=2) + "\n")


def main() -> int:
    fresh_start()
    con = duckdb.connect()
    state = {"status": "complete", "stopped_by": None, "not_written": [], "accounting": {}, "checks": []}
    print("HW3 pipeline: raw -> silver -> checks -> gold")

    def crashed(stage: str, err: BaseException) -> int:
        state["status"] = "crashed"
        state["stopped_by"] = f"{stage}: {type(err).__name__}: {err}"
        write_report(state)
        traceback.print_exc()
        print(f"\nCRASHED in {stage}: {type(err).__name__}: {err}")
        print(f"checks report: {REPORT.as_posix()} (status crashed)")
        return 1

    # 1. silver
    print("silver")
    for name in CLEANERS:
        try:
            module = importlib.import_module(f"scripts.{name}")
            accounting = module.run(con)
        except NotImplementedError:
            print(f"  {name:<22} not written yet")
            state["not_written"].append(name)
            continue
        except Exception as err:  # noqa: BLE001 - reported, then the run ends
            return crashed(name, err)
        print(f"  {name:<22} done")
        if isinstance(accounting, dict):
            source = name.removeprefix("clean_")
            state["accounting"][source] = {k: jsonable(v) for k, v in accounting.items()}
            print_accounting(source, accounting)
    views = register(con, "silver", Path("data/silver"))
    if views:
        print("  views: " + ", ".join(views))

    # 2. checks - the first family with a "stop" ends the run
    print("checks")
    try:
        checks = importlib.import_module("scripts.checks")
    except Exception as err:  # noqa: BLE001
        return crashed("checks", err)
    for family in FAMILIES:
        try:
            records = as_records(getattr(checks, f"check_{family}")(con, state["accounting"]), family)
        except NotImplementedError:
            print(f"  check_{family:<16} not written yet")
            state["not_written"].append(f"check_{family}")
            continue
        except Exception as err:  # noqa: BLE001
            return crashed(f"check_{family}", err)
        if not records:
            print(f"  check_{family:<16} returned no records")
        state["checks"].extend(records)
        for r in records:
            print(f"  [{r['action']:<10}] {r['family']:<14} {r['check']:<30} observed {fmt(r['observed'])}"
                  f" (threshold {fmt(r['threshold'])})  {r['subject']}")
            if r.get("detail"):
                print(f"               {r['detail']}")
        stops = [r for r in records if r["action"] == "stop"]
        if stops:
            state["status"] = "stopped"
            state["stopped_by"] = f"check_{family}: " + ", ".join(r["check"] for r in stops)
            write_report(state)
            print(f"\nSTOPPED by check_{family}: " + "; ".join(f"{r['check']} observed {fmt(r['observed'])}"
                                                            f" against {fmt(r['threshold'])}" for r in stops))
            print("gold was not built from silver that failed a check.")
            print(f"checks report: {REPORT.as_posix()} ({len(state['checks'])} records, status stopped)")
            return 1

    # 3. gold
    print("gold")
    try:
        report = importlib.import_module("scripts.report")
        report.run(con)
        print(f"  {'report':<22} done")
    except NotImplementedError:
        print(f"  {'report':<22} not written yet")
        state["not_written"].append("report")
    except Exception as err:  # noqa: BLE001
        return crashed("report", err)
    gold = register(con, "gold", Path("data/gold"))
    for v in gold:
        n = con.execute(f"SELECT COUNT(*) FROM {v}").fetchone()[0]
        print(f"  {v}: {n:,} rows")
    if not gold:
        print("no gold table was written")

    if state["not_written"]:
        state["status"] = "incomplete"
    write_report(state)
    print(f"checks report: {REPORT.as_posix()} ({len(state['checks'])} records, status {state['status']})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
